import type { ResourceConfig } from './resource-config';

/** Registry of CMS content modules, keyed by URL slug. */
export const CMS_RESOURCES: Record<string, ResourceConfig> = {
  products: {
    label: 'Product',
    labelPlural: 'Products',
    basePath: '/admin/cms/products',
    apiPath: '/cms/products',
    titleField: 'name',
    columns: [
      { header: 'Name', field: 'name' },
      { header: 'Code', field: 'productCode' },
      { header: 'Status', field: 'status', badge: true },
    ],
    fields: [
      { name: 'productCode', label: 'Product code', type: 'text', required: true },
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'slug', label: 'Slug', type: 'text', hint: 'Auto from name if blank' },
      { name: 'categoryId', label: 'Category', type: 'select', required: true, optionsEndpoint: '/categories' },
      { name: 'shortDescription', label: 'Short description', type: 'textarea' },
      { name: 'description', label: 'Description', type: 'richtext' },
      { name: 'fabricType', label: 'Fabric', type: 'text' },
      { name: 'moq', label: 'MOQ', type: 'number' },
      { name: 'availableSizes', label: 'Available sizes', type: 'text', hint: 'Comma-separated' },
      { name: 'availableColors', label: 'Available colours', type: 'text', hint: 'Comma-separated' },
      { name: 'isFeatured', label: 'Featured', type: 'checkbox' },
      { name: 'status', label: 'Status', type: 'status', statusKind: 'publish' },
    ],
  },
  industries: {
    label: 'Industry',
    labelPlural: 'Industries',
    basePath: '/admin/cms/industries',
    apiPath: '/cms/industries',
    titleField: 'name',
    columns: [
      { header: 'Name', field: 'name' },
      { header: 'Status', field: 'status', badge: true },
      { header: 'Updated', field: 'updatedAt' },
    ],
    fields: [
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'slug', label: 'Slug', type: 'text' },
      { name: 'description', label: 'Description', type: 'textarea' },
      { name: 'bannerImage', label: 'Banner image', type: 'media' },
      { name: 'status', label: 'Status', type: 'status', statusKind: 'record' },
    ],
  },
  blogs: {
    label: 'Blog',
    labelPlural: 'Blogs',
    basePath: '/admin/cms/blogs',
    apiPath: '/cms/blogs',
    titleField: 'title',
    columns: [
      { header: 'Title', field: 'title' },
      { header: 'Status', field: 'status', badge: true },
      { header: 'Updated', field: 'updatedAt' },
    ],
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'slug', label: 'Slug', type: 'text', hint: 'Auto from title if blank' },
      { name: 'excerpt', label: 'Excerpt', type: 'textarea' },
      { name: 'content', label: 'Content', type: 'richtext' },
      { name: 'featuredImage', label: 'Featured image', type: 'media' },
      { name: 'seoTitle', label: 'SEO title', type: 'text' },
      { name: 'seoDescription', label: 'SEO description', type: 'textarea' },
      { name: 'status', label: 'Status', type: 'status', statusKind: 'publish' },
    ],
  },
  catalogs: {
    label: 'Catalog',
    labelPlural: 'Catalogs',
    basePath: '/admin/cms/catalogs',
    apiPath: '/cms/catalogs',
    titleField: 'title',
    columns: [
      { header: 'Title', field: 'title' },
      { header: 'Category', field: 'category' },
      { header: 'Status', field: 'status', badge: true },
    ],
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'slug', label: 'Slug', type: 'text' },
      { name: 'description', label: 'Description', type: 'textarea' },
      { name: 'thumbnail', label: 'Thumbnail', type: 'media' },
      { name: 'fileUrl', label: 'File URL (PDF)', type: 'text', required: true },
      { name: 'category', label: 'Category', type: 'text' },
      { name: 'status', label: 'Status', type: 'status', statusKind: 'publish' },
    ],
  },
  'case-studies': {
    label: 'Case Study',
    labelPlural: 'Case Studies',
    basePath: '/admin/cms/case-studies',
    apiPath: '/cms/case-studies',
    titleField: 'title',
    columns: [
      { header: 'Title', field: 'title' },
      { header: 'Status', field: 'status', badge: true },
      { header: 'Updated', field: 'updatedAt' },
    ],
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'slug', label: 'Slug', type: 'text' },
      { name: 'industryId', label: 'Industry', type: 'select', optionsEndpoint: '/industries' },
      { name: 'clientName', label: 'Client name', type: 'text' },
      { name: 'location', label: 'Location', type: 'text' },
      { name: 'challenge', label: 'Challenge', type: 'textarea' },
      { name: 'solution', label: 'Solution', type: 'textarea' },
      { name: 'results', label: 'Results', type: 'textarea' },
      { name: 'featuredImage', label: 'Featured image', type: 'media' },
      { name: 'status', label: 'Status', type: 'status', statusKind: 'publish' },
    ],
  },
  testimonials: {
    label: 'Testimonial',
    labelPlural: 'Testimonials',
    basePath: '/admin/cms/testimonials',
    apiPath: '/cms/testimonials',
    titleField: 'name',
    columns: [
      { header: 'Name', field: 'name' },
      { header: 'Organization', field: 'organization' },
      { header: 'Status', field: 'status', badge: true },
    ],
    fields: [
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'organization', label: 'Organization', type: 'text' },
      { name: 'designation', label: 'Designation', type: 'text' },
      { name: 'testimonial', label: 'Testimonial', type: 'textarea', required: true },
      { name: 'photo', label: 'Photo', type: 'media' },
      { name: 'sortOrder', label: 'Sort order', type: 'number' },
      { name: 'status', label: 'Status', type: 'status', statusKind: 'publish' },
    ],
  },
};

export const CMS_MODULES = Object.entries(CMS_RESOURCES).map(([slug, c]) => ({
  slug,
  label: c.labelPlural,
}));
